CNAPP-10978-Change-all-TF-SDK-API-calls-to-use-the-new-retry-function
dome9/dome9-sdk-go pull request #142
Opened 2024-08-14 13:57 UTC by idorosCP

2024-08-14 15:11 UTC, dolevh-d9 commented on services/cloudaccounts/aws/aws.go
> +		resp, err = service.Client.NewRequestDoRetry("DELETE", relativeURL, nil, nil, nil, nil)
There is already a retry mechanism here, please delete it

2024-08-14 15:13 UTC, dolevh-d9 commented on services/integrations/integration.go
> +		resp, err = service.Client.NewRequestDoRetry("DELETE", relativeURL, nil, nil, nil, nil)
There is already a retry mechanism here, please delete it

2024-08-14 15:18 UTC, dolevh-d9 commented on dome9/client/client.go
> +		if resp.StatusCode == http.StatusTooManyRequests {
if what isn't 0?

2024-08-14 15:18 UTC, dolevh-d9 requested changes
Note the notes

2024-08-15 06:30 UTC, idorosCP commented on dome9/client/client.go
> +		if resp.StatusCode == http.StatusTooManyRequests {
'i' from the for loop, meaning for example if we received 429 on the third 'NewRequestDo' attempt, retrySleepBetweenSecs and maxRetries wont align to exactly 5 minutes. Is this a edge case I should handle?

2024-08-15 06:40 UTC, dolevh-d9 commented on dome9/client/client.go
> +		if resp.StatusCode == http.StatusTooManyRequests {
No

2024-08-15 06:42 UTC, dolevh-d9 approved these changes
Great
Please check with the provider

2024-08-18 07:47 UTC, merged